use std::io::Error;

pub async fn login() -> Result<(), Error> {
    Ok(())
}
